[renames]
eth0 = "wan"
eth1 = "lan"

[interfaces.wan]
# The WAN interface
mode = "dhcp"

[interfaces.lan]
# The LAN interface
mode = "static"
address = "10.10.99.1"
netmask = 24
do_failover = true

[interfaces.lan.dhcp]
enabled = true
netmask = "255.255.255.0"
router = "10.10.99.1"
start = "10.10.99.100"
end = "10.10.99.200"
dns = "10.10.99.1"
